# Generated by Django 5.2.7 on 2025-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0002_alter_article_options_alter_article_body_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "-published_at"], name="weblog_arti_status_b0462f_idx"
            ),
        ),
    ]
